### ISSUE TITLE
How to link the CountryController with CountryPhoneCodePicker widget

### ISSUE THREAD

**Issue by vipafattal** [samitkapoor/country_phone_code_picker#3]
I have created CountryController in the class but whenever I try to access `selectedCountry` I get an uninitialized exception and there is no clear way on how to link CountryController with CountryPhoneCodePicker.

**Comment by MoShehata7920** [comment]
haha

**Comment by samitkapoor** [comment]
Apologies for the late response. @vipafattal 
If you check it now, I have made some changes in the implementation of the package and you will not face an uninitialized exception now.
